services:
  frontend:
    image: animikhaich/free-game-tracker:frontend
    pull_policy: always
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
    depends_on:
      - backend

  backend:
    image: animikhaich/free-game-tracker:backend
    pull_policy: always
    ports:
      - "3003:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: always
