version: '3.8'

services:
  free-game-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:5173"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s